Traceback (most recent call last):
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/bose/base_task.py", line 117, in run_task
    self.run(driver)
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 278, in run
    result = get_data(self.scroll_times)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 266, in get_data
    a = get_maps_data(links)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 245, in get_maps_data
    ls = list(map(get_data, links))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 226, in get_data
    sharing[4].click()
    ~~~~~~~^^^
IndexError: list index out of range
