Traceback (most recent call last):
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/bose/base_task.py", line 117, in run_task
    self.run(driver)
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 242, in run
    write(result)
             ^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 230, in get_data
    new_results = do_filter(a, filter_data)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 209, in get_maps_data
    return ls
         ^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 197, in get_data
    ActionChains(driver).send_keys(Keys.ESCAPE).perform()
                                     ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get_attribute'
