Traceback (most recent call last):
  File "/home/vagif/Documents/remote/bionluk/googleMapScraper/.venv/lib/python3.10/site-packages/bose/base_task.py", line 117, in run_task
    self.run(driver)
  File "/home/vagif/Documents/remote/bionluk/googleMapScraper/src/scraper.py", line 291, in run
    result = get_data(self.scroll_times)
  File "/home/vagif/Documents/remote/bionluk/googleMapScraper/src/scraper.py", line 279, in get_data
    a = get_maps_data(links)
  File "/home/vagif/Documents/remote/bionluk/googleMapScraper/src/scraper.py", line 258, in get_maps_data
    ls = list(map(get_data, links))
  File "/home/vagif/Documents/remote/bionluk/googleMapScraper/src/scraper.py", line 233, in get_data
    sharing[4].click()
IndexError: list index out of range
