Traceback (most recent call last):
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 198, in get_data
    opened_days[1].click()
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=113.0.5672.126)
Stacktrace:
#0 0x5623b1a26b73 <unknown>
#1 0x5623b176f2a0 <unknown>
#2 0x5623b17acf94 <unknown>
#3 0x5623b17a1e8a <unknown>
#4 0x5623b17cb632 <unknown>
#5 0x5623b17a17b3 <unknown>
#6 0x5623b17cb7fe <unknown>
#7 0x5623b17e3b3e <unknown>
#8 0x5623b17cb403 <unknown>
#9 0x5623b179ff0a <unknown>
#10 0x5623b17a0ffe <unknown>
#11 0x5623b19e7c4e <unknown>
#12 0x5623b19eb8f2 <unknown>
#13 0x5623b19f4870 <unknown>
#14 0x5623b19ec933 <unknown>
#15 0x5623b19c075e <unknown>
#16 0x5623b1a0ee48 <unknown>
#17 0x5623b1a0efd7 <unknown>
#18 0x5623b1a1ee39 <unknown>
#19 0x7f1acac94b43 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/bose/base_task.py", line 117, in run_task
    self.run(driver)
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 260, in run
    result = get_data()
             ^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 248, in get_data
    a = get_maps_data(links)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 227, in get_maps_data
    ls = list(map(get_data, links))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 201, in get_data
    opened_days[0].click()
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=113.0.5672.126)
Stacktrace:
#0 0x5623b1a26b73 <unknown>
#1 0x5623b176f2a0 <unknown>
#2 0x5623b17acf94 <unknown>
#3 0x5623b17a1e8a <unknown>
#4 0x5623b17cb632 <unknown>
#5 0x5623b17a17b3 <unknown>
#6 0x5623b17cb7fe <unknown>
#7 0x5623b17e3b3e <unknown>
#8 0x5623b17cb403 <unknown>
#9 0x5623b179ff0a <unknown>
#10 0x5623b17a0ffe <unknown>
#11 0x5623b19e7c4e <unknown>
#12 0x5623b19eb8f2 <unknown>
#13 0x5623b19f4870 <unknown>
#14 0x5623b19ec933 <unknown>
#15 0x5623b19c075e <unknown>
#16 0x5623b1a0ee48 <unknown>
#17 0x5623b1a0efd7 <unknown>
#18 0x5623b1a1ee39 <unknown>
#19 0x7f1acac94b43 <unknown>

