Traceback (most recent call last):
  File "/home/va/Documents/remote/google-maps-scraper/venv/lib/python3.11/site-packages/bose/base_task.py", line 117, in run_task
    self.run(driver)
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 359, in run
    result = get_data(self.scroll_times)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 347, in get_data
    a = get_maps_data(links)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 326, in get_maps_data
    ls = list(map(get_data, links))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/va/Documents/remote/google-maps-scraper/src/scraper.py", line 271, in get_data
    n = lsc[0]
        ~~~^^^
IndexError: list index out of range
